-- 赛程表（sports_meeting.schedule_id 的关联表）
CREATE TABLE IF NOT EXISTS schedule (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '赛程ID',
    sports_meeting_id BIGINT NOT NULL COMMENT '所属运动会ID',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='赛程表';

-- 签名表（sports_meeting.sign_sheet_id 的关联表）
CREATE TABLE IF NOT EXISTS sign_sheet (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '签名表ID',
    sports_meeting_id BIGINT NOT NULL COMMENT '所属运动会ID',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='签名表';

-- 选手名单表（sports_meeting.player_list_id 的关联表）
CREATE TABLE IF NOT EXISTS player_list (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '选手名单ID',
    sports_meeting_id BIGINT NOT NULL COMMENT '所属运动会ID',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='选手名单表';

-- 比赛项目表（sports_meeting.event_id 的关联表）
CREATE TABLE IF NOT EXISTS event (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '比赛项目ID',
    sports_meeting_id BIGINT NOT NULL COMMENT '所属运动会ID',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='比赛项目表';

-- 成绩公告表（sports_meeting.result_id 的关联表）
CREATE TABLE IF NOT EXISTS result (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '成绩公告ID',
    sports_meeting_id BIGINT NOT NULL COMMENT '所属运动会ID',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='成绩公告表';

-- 赛事通知表（sports_meeting.notice_id 的关联表）
CREATE TABLE IF NOT EXISTS notice (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '赛事通知ID',
    sports_meeting_id BIGINT NOT NULL COMMENT '所属运动会ID',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='赛事通知表';

-- 申述表（sports_meeting.appeal_id 的关联表）
CREATE TABLE IF NOT EXISTS appeal (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '申述表ID',
    sports_meeting_id BIGINT NOT NULL COMMENT '所属运动会ID',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='申述表';
