-- 项目规则表（与 event 逻辑外键关联，字段后续补充）
CREATE TABLE IF NOT EXISTS rule (
    id          BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '规则ID',
    event_id    BIGINT       NOT NULL COMMENT '关联的比赛项目ID（逻辑外键）',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP NULL COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='项目规则表';
